#!/bin/bash
# [Gedit Tool]
# Name=Run
# Shortcut=<Primary>r
# Languages=
# Applicability=local
# Output=output-panel
# Input=document
# Save-files=document

PATH=$HOME/local/bin:$PATH
name=$GEDIT_CURRENT_DOCUMENT_NAME

case "${name##*.}" in
  coffee) coffee $name;;
  js    ) node $name;;
  py    ) python $name;;
  rb    ) ruby $name;;
  sh    ) bash $name;;
  *     ) echo "I do not know how to run $name";;
esac
